/* Sonora UI — semantic, dependency-free educational interface */
(() => {
  const A = 'assets/';
  const svg = (d, extra='') => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" ${extra}>${d}</svg>`;
  const icons = {
    home: svg('<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1Z"/>'),
    search: svg('<circle cx="11" cy="11" r="6.7"/><path d="m16 16 4.2 4.2"/>'),
    library: svg('<path d="M4 22V4M9 4v18M4 9h5M14 4h6v18h-6"/>'),
    plus: svg('<path d="M12 5v14M5 12h14"/>'),
    arrowLeft: svg('<path d="m15 18-6-6 6-6"/>'), arrowRight: svg('<path d="m9 18 6-6-6-6"/>'),
    chevron: svg('<path d="m6 9 6 6 6-6"/>'), menu: svg('<path d="M4 7h16M4 12h16M4 17h16"/>'),
    play: svg('<path fill="currentColor" stroke="none" d="m8 5 11 7-11 7z"/>'), pause: svg('<path fill="currentColor" stroke="none" d="M7 5h3.8v14H7zm6.2 0H17v14h-3.8z"/>'),
    previous: svg('<path d="M6 5v14M18 6l-9 6 9 6z"/>'), next: svg('<path d="M18 5v14M6 6l9 6-9 6z"/>'),
    shuffle: svg('<path d="M3 7h3.5c4.5 0 6 10 10.5 10H21"/><path d="m18 14 3 3-3 3M3 17h3.5c1.1 0 2-.6 2.8-1.5M15.5 8.5C16 7.6 16.6 7 17.5 7H21"/><path d="m18 4 3 3-3 3"/>'),
    repeat: svg('<path d="M17 2l4 4-4 4"/><path d="M3 11V9a3 3 0 0 1 3-3h15M7 22l-4-4 4-4"/><path d="M21 13v2a3 3 0 0 1-3 3H3"/>'),
    heart: (filled=false) => svg('<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 5.9l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.9-8.4a5.5 5.5 0 0 0-.1-7.8Z" '+(filled?'fill="currentColor"':'')+'/>'),
    dots: svg('<circle cx="5" cy="12" r=".8" fill="currentColor"/><circle cx="12" cy="12" r=".8" fill="currentColor"/><circle cx="19" cy="12" r=".8" fill="currentColor"/>'),
    clock: svg('<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>'),
    download: svg('<path d="M12 3v12M7 10l5 5 5-5"/><path d="M5 21h14"/>'),
    bell: svg('<path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>'),
    volume: svg('<path d="M4 10v4h4l5 4V6L8 10Z"/><path d="M16 9a4 4 0 0 1 0 6M18.5 6.5a7.5 7.5 0 0 1 0 11"/>'),
    volumeX: svg('<path d="M4 10v4h4l5 4V6L8 10Z"/><path d="m17 10 4 4m0-4-4 4"/>'),
    queue: svg('<path d="M4 6h16M4 12h16M4 18h10"/>'),
    device: svg('<rect x="3" y="5" width="18" height="12" rx="1"/><path d="M8 21h8M12 17v4"/>'),
    fullscreen: svg('<path d="M8 3H3v5M16 3h5v5M21 16v5h-5M3 16v5h5"/>'),
    lyrics: svg('<path d="M5 4h14v16H5z"/><path d="M8 9h8M8 13h8M8 17h4"/>'),
    filter: svg('<path d="M4 5h16M7 12h10M10 19h4"/>'),
    grid: svg('<rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><rect x="14" y="14" width="6" height="6"/>'),
    list: svg('<path d="M8 6h12M8 12h12M8 18h12"/><circle cx="4" cy="6" r="1" fill="currentColor"/><circle cx="4" cy="12" r="1" fill="currentColor"/><circle cx="4" cy="18" r="1" fill="currentColor"/>'),
    check: svg('<path d="m5 12 4 4L19 6"/>'),
    moon: svg('<path d="M20.5 15.4A8.4 8.4 0 0 1 8.6 3.5 8.5 8.5 0 1 0 20.5 15.4Z"/>'),
    sun: svg('<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/>'),
    pin: svg('<path d="M12 17v5M7 4l13 13M15 3l6 6-3 1-4 4-1 3-6-6 3-1 4-4Z"/>')
  };
  window.SonoraIcons = icons;

  const tracks = [
    {id:'midnight-code',language:'English',title:'Midnight Compiler',artist:'Dev Moon',album:'Midnight Code',date:'Jun 28, 2026',duration:22,audio:A+'audio/midnight-code.wav',art:A+'albums/midnight-code.svg',category:'coding focus synthwave',description:'Deep focus beats for the last commit.'},
    {id:'violet-hour',title:'Midnight Signal',artist:'Aria Nova',album:'English Pop Now',language:'English',date:'Jun 17, 2026',duration:22,audio:A+'audio/violet-hour.wav',art:A+'albums/violet-hour.svg',category:'pop chill electronic',description:'Dreamy electronic pop for blue-hour drives.'},
    {id:'neon-run',language:'English',title:'After the Exit',artist:'Kai Noir',album:'Neon Run',date:'May 31, 2026',duration:22,audio:A+'audio/neon-run.wav',art:A+'albums/neon-run.svg',category:'edm workout night drive',description:'High voltage tracks with no speed limit.'},
    {id:'paper-skies',language:'English',title:'Folded Light',artist:'Mira Sol',album:'Paper Skies',date:'May 22, 2026',duration:22,audio:A+'audio/paper-skies.wav',art:A+'albums/paper-skies.svg',category:'indie pop chill',description:'Warm melodies and unhurried afternoons.'},
    {id:'focus-flow',language:'Instrumental',title:'The Quiet Loop',artist:'Luma Field',album:'Focus Flow',date:'May 11, 2026',duration:22,audio:A+'audio/focus-flow.wav',art:A+'albums/focus-flow.svg',category:'focus instrumental ambient',description:'Instrumentals designed to make room for thought.'},
    {id:'afterglow',title:'Rangon Ki Shaam',artist:'Mira Sol',album:'Hindi Pop Now',language:'Hindi',date:'Apr 29, 2026',duration:22,audio:A+'audio/afterglow.wav',art:A+'albums/afterglow.svg',category:'pop indian hits',description:'A little sunlight left in every chorus.'},
    {id:'city-rain',language:'Instrumental',title:'Window Seat',artist:'Kai Noir',album:'City Rain',date:'Apr 18, 2026',duration:22,audio:A+'audio/city-rain.wav',art:A+'albums/city-rain.svg',category:'lofi chill rain',description:'Soft beats for a city in the rain.'},
    {id:'golden-tape',language:'English',title:'Side B, Summer',artist:'The Static',album:'Golden Tape',date:'Mar 30, 2026',duration:22,audio:A+'audio/golden-tape.wav',art:A+'albums/golden-tape.svg',category:'rock retro indie',description:'Guitar glow with a cassette heart.'},
    {id:'echo-park',language:'Instrumental',title:'Green Room',artist:'Dev Moon',album:'Echo Park',date:'Mar 16, 2026',duration:22,audio:A+'audio/echo-park.wav',art:A+'albums/echo-park.svg',category:'jazz instrumental',description:'Loose jazz lines after sundown.'},
    {id:'pulse-check',language:'English',title:'Heart Rate',artist:'Aria Nova',album:'Pulse Check',date:'Feb 26, 2026',duration:22,audio:A+'audio/pulse-check.wav',art:A+'albums/pulse-check.svg',category:'workout pop edm',description:'An instant rush of kinetic pop.'},
    {id:'indigo-monsoon',title:'వాన వెలుగు (Vana Velugu)',artist:'Nadiya',album:'Telugu Pulse',language:'Telugu',date:'Feb 8, 2026',duration:22,audio:A+'audio/indigo-monsoon.wav',art:A+'albums/indigo-monsoon.svg',category:'indian pop chill monsoon',description:'Indian pop washed in indigo tones.'},
    {id:'solaris',language:'Instrumental',title:'First Light',artist:'Luma Field',album:'Solaris',date:'Jan 19, 2026',duration:22,audio:A+'audio/solaris.wav',art:A+'albums/solaris.svg',category:'classical instrumental focus',description:'Cinematic instrumental sunrises.'},
    {id:'lofi-desk',language:'Instrumental',title:'Tab Open',artist:'Dev Moon',album:'Lo-Fi Desk',date:'Jan 8, 2026',duration:22,audio:A+'audio/lofi-desk.wav',art:A+'albums/lofi-desk.svg',category:'coding lofi focus',description:'Gentle loops for the desk-bound dreamer.'},
    {id:'jazz-room',language:'Instrumental',title:'Low Ceiling',artist:'The Static',album:'Jazz Room',date:'Dec 17, 2025',duration:22,audio:A+'audio/jazz-room.wav',art:A+'albums/jazz-room.svg',category:'jazz late night',description:'Late night jazz from the back room.'}
  ];
  /* Text-only, original placeholder posters for the requested cinema and English discovery shelves. Each item uses an original bundled preview, never an official soundtrack. */
  const movieSpecs = [
    ['pushpa-2','Pushpa 2','Telugu','Cinematic Telugu'],['kalki-2898','Kalki 2898 AD','Telugu','Cinematic Telugu'],['salaar','Salaar','Telugu','Cinematic Telugu'],['rrr','RRR','Telugu','Cinematic Telugu'],['baahubali','Baahubali','Telugu','Cinematic Telugu'],['devara','Devara','Telugu','Cinematic Telugu'],['og','OG','Telugu','Cinematic Telugu'],['game-changer','Game Changer','Telugu','Cinematic Telugu'],['lucky-baskhar','Lucky Baskhar','Telugu','Cinematic Telugu'],['sita-ramam','Sita Ramam','Telugu','Cinematic Telugu'],['hi-nanna','Hi Nanna','Telugu','Cinematic Telugu'],
    ['animal','Animal','Hindi','Cinematic Hindi'],['jawan','Jawan','Hindi','Cinematic Hindi'],['pathaan','Pathaan','Hindi','Cinematic Hindi'],['kgf','KGF','Kannada','Cinematic Kannada'],['kantara','Kantara','Kannada','Cinematic Kannada'],['leo','Leo','Tamil','Cinematic Tamil'],['vikram','Vikram','Tamil','Cinematic Tamil'],['master','Master','Tamil','Cinematic Tamil'],['amaran','Amaran','Tamil','Cinematic Tamil'],['premalu','Premalu','Malayalam','Cinematic Malayalam'],['aavesham','Aavesham','Malayalam','Cinematic Malayalam'],['marco','Marco','Malayalam','Cinematic Malayalam'],['cinema-dawn','Cinema Dawn','Hindi','Cinematic Hindi']
  ];
  const englishSpecs = [['taylor-swift','Taylor Swift'],['ed-sheeran','Ed Sheeran'],['the-weeknd','The Weeknd'],['imagine-dragons','Imagine Dragons'],['billie-eilish','Billie Eilish'],['dua-lipa','Dua Lipa'],['bruno-mars','Bruno Mars'],['coldplay','Coldplay'],['onerepublic','OneRepublic'],['maroon-5','Maroon 5']];
  const previewAudio = ['midnight-code','violet-hour','neon-run','paper-skies','focus-flow','afterglow','city-rain','golden-tape','echo-park','pulse-check','indigo-monsoon','solaris','lofi-desk','jazz-room'];
  const movieTracks = movieSpecs.map(([id,album,language,artist],i)=>({id,title:`${album} — Original Theme`,artist,album,language,date:'Jul 20, 2026',duration:22,audio:A+`audio/${previewAudio[i%previewAudio.length]}.wav`,art:A+`albums/${id}.svg`,category:`${language.toLowerCase()} movie soundtrack cinematic trending`,description:'Original placeholder cinematic preview — not an official soundtrack.'}));
  const englishTracks = englishSpecs.map(([id,artist],i)=>({id,title:`${artist} — Pop Preview`,artist,album:artist,language:'English',date:'Jul 20, 2026',duration:22,audio:A+`audio/${previewAudio[(i+4)%previewAudio.length]}.wav`,art:A+`albums/${id}.svg`,category:'english pop hollywood international trending',description:'Original placeholder pop preview — not an official release.'}));
  tracks.push(...movieTracks,...englishTracks);
  const artists = [
    {name:'Aria Nova', listeners:'12,843,219 monthly listeners',image:A+'artists/aria-nova.svg'}, {name:'Kai Noir',listeners:'8,219,431 monthly listeners',image:A+'artists/kai-noir.svg'}, {name:'Mira Sol',listeners:'6,924,117 monthly listeners',image:A+'artists/mira-sol.svg'}, {name:'The Static',listeners:'5,107,832 monthly listeners',image:A+'artists/the-static.svg'}, {name:'Dev Moon',listeners:'3,544,920 monthly listeners',image:A+'artists/dev-moon.svg'}, {name:'Nadiya',listeners:'2,809,351 monthly listeners',image:A+'artists/nadiya.svg'}
  ];
  const page = document.body.dataset.page || 'home';
  const currentFile = `${page}.html`;
  const esc = value => String(value).replace(/[&<>'"]/g,c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmt = seconds => `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
  const track = id => tracks.find(t => t.id === id) || tracks[0];
  const cardGlow = t => ({'midnight-code':'#1d2446','violet-hour':'#3a214b','neon-run':'#123551','paper-skies':'#4c3544','focus-flow':'#183b3d','afterglow':'#4c321d','city-rain':'#29394d','golden-tape':'#48351f','echo-park':'#214129','pulse-check':'#48232b','indigo-monsoon':'#24336d','solaris':'#4a3c1e','lofi-desk':'#4c3031','jazz-room':'#302143'}[t.id] || '#202028');
  const card = (t, artist=false) => artist ? `<article class="music-card artist" data-search="${esc(t.name)} artist ${esc(t.listeners)}" tabindex="0"><div class="art-wrap"><img loading="lazy" src="${t.image}" alt="Original illustrated portrait of ${esc(t.name)}" /></div><span class="card-title">${esc(t.name)} <i class="verified">✓</i></span><span class="card-subtitle">${esc(t.listeners)}</span></article>` : `<article class="music-card" style="--card-glow:${cardGlow(t)}" data-search="${esc(t.title+' '+t.artist+' '+t.album+' '+t.category+' '+(t.language||''))}" data-track="${t.id}" tabindex="0"><div class="art-wrap"><img loading="lazy" src="${t.art}" alt="${esc(t.album)} original artwork" /><button class="card-play" data-play-track="${t.id}" aria-label="Play ${esc(t.title)}">${icons.play}</button></div><span class="card-title">${esc(t.album)}</span><span class="card-subtitle">${esc(t.description)}</span><small class="language-tag">${esc(t.language || 'Original')}</small></article>`;
  const quickCard = t => `<article class="quick-card" data-track="${t.id}" tabindex="0"><img src="${t.art}" alt=""/><span>${esc(t.album)}</span><button class="quick-play" data-play-track="${t.id}" aria-label="Play ${esc(t.album)}">${icons.play}</button></article>`;
  const songRow = (t, i, includeAlbum=true) => `<tr class="song-row" data-track-row="${t.id}" data-track="${t.id}" tabindex="0"><td><span class="track-num">${i+1}</span><span class="eq">▮▮▮</span></td><td><div class="song-main"><img loading="lazy" src="${t.art}" alt=""/><div><b>${esc(t.title)}</b><small>${esc(t.artist)}</small></div></div></td>${includeAlbum?`<td>${esc(t.album)}</td>`:''}<td>${esc(t.date)}</td><td>${fmt(t.duration)} <button class="fav ${window.player?.isLiked(t.id)?'active':''}" data-like-track="${t.id}" aria-label="Like ${esc(t.title)}">${icons.heart(window.player?.isLiked(t.id))}</button></td></tr>`;
  const songTable = (list, includeAlbum=true) => `<table class="song-table"><thead><tr><th>#</th><th>Title</th>${includeAlbum?'<th>Album</th>':''}<th>Date added</th><th>${icons.clock}</th></tr></thead><tbody>${list.map((t,i)=>songRow(t,i,includeAlbum)).join('')}</tbody></table>`;
  const section = (title, list, show=true, type='tracks') => { const id=title.toLowerCase().replace(/[^a-z0-9]+/g,'-'); return `<section class="section carousel-section" id="${id}"><div class="section-head"><h2>${title}</h2><div class="section-actions"><button class="carousel-arrow" data-carousel-prev aria-label="Scroll ${esc(title)} backward">${icons.arrowLeft}</button><button class="carousel-arrow" data-carousel-next aria-label="Scroll ${esc(title)} forward">${icons.arrowRight}</button>${show?'<a class="show-all" href="library.html">Show all</a>':''}</div></div><div class="carousel"><div class="card-row" data-carousel-track>${type === 'artists' ? list.map(a=>card(a,true)).join('') : list.map(t=>card(t)).join('')}</div></div></section>`; };

  function sidebar() {
    const libraries = [
      ['Liked Songs','Playlist • your wishlist','liked','♥'],['Recently Played','Playlist • Made for you','recently','◷'],['Top Telugu','Playlist • cinematic & new','pushpa-2',''],['Top Hindi','Playlist • cinematic & new','animal',''],['Tamil Hits','Playlist • cinematic & new','leo',''],['Malayalam Hits','Playlist • cinematic & new','premalu',''],['English Pop','Playlist • global picks','taylor-swift',''],['Hollywood','Playlist • global picks','the-weeknd',''],['Lo-Fi Focus','Playlist • Sonora','lofi-desk',''],['Workout','Playlist • Sonora','pulse-check','']];
    const mini = ([name,meta,id,symbol]) => { const t=track(id); const special=id==='liked'||id==='recently'; return `<a href="${id==='liked'?'liked.html':id==='recently'?'recently.html':id==='midnight-code'?'playlist.html':'library.html'}" class="mini-playlist library-entry playlist-entry"><div class="${special?'mini-placeholder '+(id==='liked'?'liked':''):'mini-art'}">${special?symbol:`<img src="${t.art}" alt=""/>`}</div><div class="mini-info"><b>${name}</b><span>${id==='liked'?'<i class="pin">●</i>':''}${meta}</span></div></a>`; };
    const miniArtist = a => `<a href="search.html?q=${encodeURIComponent(a.name)}" class="mini-playlist library-entry artist-entry" hidden><img src="${a.image}" alt=""/><div class="mini-info"><b>${a.name}</b><span>Artist · ${a.listeners}</span></div></a>`;
    return `<aside class="sidebar" id="sidebar"><div class="side-top"><a class="side-logo" href="home.html"><img src="${A}logo/sonora-mark.svg" alt=""/>sonora</a><nav class="side-nav" aria-label="Primary"><a href="home.html" class="${page==='home'?'active':''}">${icons.home}<span>Home</span></a><a href="search.html" class="${page==='search'?'active':''}">${icons.search}<span>Search</span></a></nav></div><section class="side-library" aria-label="Your Library"><a class="library-heading" href="library.html"><span class="heading-start">${icons.library}<span>Your Library</span></span><span class="library-actions"><button data-create-playlist title="Create playlist" aria-label="Create playlist">${icons.plus}</button><button data-close-sidebar class="mobile-only" aria-label="Close sidebar">×</button></span></a><div class="side-filters"><button class="active" data-library-filter="playlists">Playlists</button><button data-library-filter="artists">Artists</button></div><div class="side-search"><button title="Search in Your Library" aria-label="Search library">${icons.search}</button><span>Recents ${icons.list}</span></div><div class="library-playlists" data-library-list>${libraries.map(mini).join('')}${artists.map(miniArtist).join('')}</div></section><footer class="sidebar-foot"><a href="settings.html">Legal</a><a href="settings.html">Privacy</a><a href="settings.html">Cookies</a><a href="settings.html">Accessibility</a><a href="settings.html">Install App</a><a class="language" href="settings.html">◎ English</a></footer></aside><div class="drawer-scrim" data-close-sidebar></div>`;
  }
  function topbar() { const user=localStorage.getItem('sonora-user'),isLight=localStorage.getItem('sonora-theme')==='light'; const account=user?`<button class="avatar-btn" data-profile title="Open profile"><span>${esc(user.slice(0,2).toUpperCase())}</span><span>${esc(user)}</span>${icons.chevron}</button>`:`<><button class="auth-signup" data-auth="signup">Sign up</button><button class="auth-signin" data-auth="signin">Sign in</button></>`; return `<header class="topbar"><div class="header-left"><button class="round-btn mobile-menu" data-open-sidebar aria-label="Open menu">${icons.menu}</button><button class="round-btn" onclick="history.back()" aria-label="Go back">${icons.arrowLeft}</button><button class="round-btn" onclick="history.forward()" aria-label="Go forward">${icons.arrowRight}</button></div><div class="header-right"><label class="search-wrap">${icons.search}<span class="sr-only">Search Sonora</span><input id="global-search" type="search" autocomplete="off" placeholder="What do you want to play?" /></label><button class="round-btn theme-toggle" data-theme-toggle title="${isLight?'Switch to dark mode':'Switch to light mode'}" aria-label="${isLight?'Switch to dark mode':'Switch to light mode'}">${isLight?icons.moon:icons.sun}</button><button class="premium-btn" data-premium>Explore Premium</button><button class="install-btn" data-install>${icons.download} Install App</button><button class="round-btn hide-laptop" data-notifications aria-label="Notifications">${icons.bell}</button>${account}</div></header>`; }
  function playerMarkup() { return `<footer class="player" aria-label="Music player"><div class="now-playing"><img class="player-cover" data-player-cover src="${tracks[0].art}" alt=""/><div class="track-text"><b data-player-title>Midnight Compiler</b><span data-player-artist>Dev Moon</span><small class="language-tag" data-player-language>English</small></div><span class="eq-holder"></span><button class="heart-player" data-player-action="like" aria-label="Like current song">${icons.heart()}</button></div><div class="player-center"><div class="player-buttons"><button class="control" data-player-action="shuffle" title="Shuffle">${icons.shuffle}</button><button class="control" data-player-action="previous" title="Previous">${icons.previous}</button><button class="control play-main" data-player-action="toggle" aria-label="Play">${icons.play}</button><button class="control" data-player-action="next" title="Next">${icons.next}</button><button class="control" data-player-action="repeat" title="Repeat">${icons.repeat}</button></div><div class="progress-line"><span class="time" data-current-time>0:00</span><div class="range" data-range="progress" aria-label="Seek"><div class="range-bg"><div class="range-fill" data-progress-fill></div></div><i class="range-thumb" data-progress-thumb></i></div><span class="time" data-duration>3:33</span></div></div><div class="player-right"><button data-player-action="lyrics" title="Lyrics">${icons.lyrics}</button><button data-player-action="queue" title="Queue">${icons.queue}</button><button class="hide-laptop" title="Connect to a device">${icons.device}<i class="device-dot"></i></button><div class="volume-wrap"><button data-player-action="mute" title="Mute">${icons.volume}</button><div class="range" data-range="volume" aria-label="Volume"><div class="range-bg"><div class="range-fill" data-volume-fill></div></div><i class="range-thumb" data-volume-thumb></i></div></div><button class="hide-laptop" title="Full screen">${icons.fullscreen}</button></div></footer>`; }
  function queueMarkup(){ return `<aside class="queue-panel" id="queue-panel" aria-label="Queue"><button class="queue-close" data-close-queue aria-label="Close queue">×</button><h2>Queue</h2><p style="color:#b3b3b3;font-size:12px;margin:-12px 0 14px">Next from your coding session</p>${tracks.slice(1,7).map(t=>`<div class="queue-item" data-track="${t.id}"><img src="${t.art}" alt=""/><div><b>${t.title}</b><span>${t.artist} · ${fmt(t.duration)}</span></div></div>`).join('')}</aside>`; }

  function home() {
    const hour = new Date().getHours(), greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
    const by = (phrase, fallback=tracks.slice(0,8)) => { const result=tracks.filter(t=>t.category.includes(phrase)||t.language.toLowerCase()===phrase); return result.length?result:fallback; };
    const history=(JSON.parse(localStorage.getItem('sonora-recent')||'[]').map(track).filter(Boolean));
    const shelves = [
      ['Recently Played',history.length?history:tracks.slice(0,8)], ['Made For You',tracks.slice(0,8)], ['Because You Listened To',by('coding',tracks.slice(0,8))], ['Trending Now',movieTracks.slice(0,10)], ['Fresh Finds',englishTracks.slice(0,10)],
      ['Top Telugu',movieTracks.filter(t=>t.language==='Telugu')], ['Top Hindi',movieTracks.filter(t=>t.language==='Hindi')], ['Tamil Hits',movieTracks.filter(t=>t.language==='Tamil')], ['Malayalam Hits',movieTracks.filter(t=>t.language==='Malayalam')], ['English Pop',englishTracks], ['Hollywood',englishTracks.slice().reverse()],
      ['Lo-Fi',by('lofi')], ['Workout',by('workout')], ['Chill',by('chill')], ['Focus',by('focus')], ['Party',[track('neon-run'),track('pulse-check'),...englishTracks.slice(0,6)]], ['Road Trip',[track('city-rain'),track('golden-tape'),track('violet-hour'),...englishTracks.slice(4,9)]], ['Romantic',[track('afterglow'),track('indigo-monsoon'),track('paper-skies'),...movieTracks.filter(t=>t.album==='Sita Ramam'||t.album==='Hi Nanna'||t.album==='Premalu')]], ['90’s Hits',[track('golden-tape'),track('jazz-room'),track('paper-skies'),...englishTracks.slice(5)]], ['2025 Hits',tracks.slice(3,12)],
      ['Top Charts',movieTracks.slice(8,18)], ['New Releases',movieTracks.slice(18).concat(englishTracks.slice(0,4))], ['Recommended',[track('focus-flow'),track('solaris'),track('lofi-desk'),track('midnight-code'),...movieTracks.slice(0,4)]], ['Featured Albums',movieTracks.slice(0,8)], ["Editor's Pick",[track('sita-ramam'),track('echo-park'),track('indigo-monsoon'),track('solaris'),...englishTracks.slice(0,3)]], ['Trending Podcasts',[track('jazz-room'),track('lofi-desk'),track('focus-flow'),track('city-rain')],false], ['Your Mixes',[track('midnight-code'),track('pulse-check'),track('city-rain'),track('afterglow'),track('neon-run'),track('focus-flow')]]
    ];
    return `<div class="content"><div class="welcome-row"><h1 class="page-heading">${greeting}</h1><span class="clock">${new Date().toLocaleDateString('en-IN',{weekday:'long',month:'short',day:'numeric'})}</span></div><div class="quick-grid">${tracks.slice(0,6).map(quickCard).join('')}</div>${shelves.slice(0,2).map(([title,list,show])=>section(title,list,show!==false)).join('')}${section('Popular Artists',artists,true,'artists')}${shelves.slice(2).map(([title,list,show])=>section(title,list,show!==false)).join('')}</div>`;
  }
  function playlist() { const playlistTracks=tracks.slice(0,10); return `<div class="content"><section class="page-hero"><img class="hero-cover" src="${A}albums/midnight-code.svg" alt="Midnight Code cover"/><div class="hero-meta"><div class="overline">PUBLIC PLAYLIST</div><h1>My Coding Mix</h1><p>Instrumental focus, lo-fi loops and just enough voltage to make the next commit.</p><div class="byline"><b>Sonora</b> · 10 songs, about 36 min</div></div></section><div class="hero-actions-row"><button class="big-play" data-play-track="midnight-code" aria-label="Play My Coding Mix">${icons.play}</button><button class="action-icon" data-collection-like title="Save to your library">${icons.heart()}</button><button class="action-icon" data-download title="Download playlist">${icons.download}</button><button class="action-icon dots" title="More options">•••</button></div>${songTable(playlistTracks)}</div>`; }
  function liked() { const liked=tracks.filter(t=>window.player?.isLiked(t.id)); return `<div class="content"><section class="page-hero" style="background:linear-gradient(145deg,#503aaf,#202040 60%,#121212)"><div class="hero-cover" style="background:linear-gradient(135deg,#48329b,#b0c4e8);display:grid;place-items:center;font-size:70px">♥</div><div class="hero-meta"><div class="overline">PLAYLIST</div><h1>Liked Songs</h1><p>Every track you have saved in one place.</p><div class="byline"><b>Priya</b> · ${liked.length} songs</div></div></section><div class="hero-actions-row"><button class="big-play" data-play-track="${liked[0]?.id||'midnight-code'}">${icons.play}</button><button class="action-icon active" data-collection-like>${icons.heart(true)}</button><button class="action-icon dots">•••</button></div>${liked.length?songTable(liked):`<div class="empty-state"><div>${icons.heart()}<h2>Songs you like will appear here</h2><p>Tap the heart on any song to save it.</p><a class="cta" href="home.html">Find something to love</a></div></div>`}</div>`; }
  function recently() { const recentIds=JSON.parse(localStorage.getItem('sonora-recent')||'[]');const recent=recentIds.map(track).filter(Boolean);const content=recent.length?recent:tracks.slice(0,7);return `<div class="content"><div class="library-toolbar"><h1>Recently played</h1></div><div class="chip-row"><button class="chip active">All</button><button class="chip">Songs</button><button class="chip">Playlists</button></div>${section('Jump back in',content,false)}<section class="section"><div class="section-head"><h2>History</h2></div>${songTable(content)}</section></div>`; }
  function searchPage() { const params=new URLSearchParams(location.search),q=params.get('q')||''; return `<div class="content"><section class="search-intro"><h1>Search</h1><p>Find songs, artists, albums and playlists made for every mood.</p></section><div class="chip-row"><button class="chip active">All</button><button class="chip">Songs</button><button class="chip">Artists</button><button class="chip">Albums</button><button class="chip">Playlists</button></div><div id="search-results">${searchResults(q)}</div></div>`; }
  function searchResults(query='') { const found=tracks.filter(t=>window.SonoraSearch.matches(t,query)); if(query && !found.length) return `<div class="empty-state"><div>${icons.search}<h2>No results for “${esc(query)}”</h2><p>Try another song, artist or mood.</p></div></div>`; if(query) return `<h2 class="search-results-title">Results for “${esc(query)}”</h2><section class="section">${songTable(found)}</section><section class="section"><div class="section-head"><h2>Albums</h2></div><div class="card-row">${found.map(t=>card(t)).join('')}</div></section>`; const genres=[['Pop','afterglow'],['Rock','golden-tape'],['Hip-Hop','pulse-check'],['EDM','neon-run'],['Lo-Fi','lofi-desk'],['Classical','solaris'],['Instrumental','focus-flow'],['Jazz','jazz-room'],['Workout','pulse-check'],['Sleep','city-rain'],['Coding','midnight-code'],['Study','paper-skies'],['Focus','focus-flow'],['Meditation','solaris'],['Travel','city-rain']]; return `<section class="section"><div class="section-head"><h2>Browse all</h2></div><div class="genre-grid">${genres.map(([name,id])=>`<button class="genre-card" data-search-genre="${id}">${name}<img src="${track(id).art}" alt=""/></button>`).join('')}</div></section>${section('Start with a mood',tracks.slice(0,6))}`; }
  function library() { const collections=[['Liked Songs','Playlist · ${n} songs','liked',null],['Top Telugu','Playlist · Cinema and new releases','pushpa-2',track('pushpa-2').art],['Top Hindi','Playlist · Cinema and new releases','animal',track('animal').art],['Tamil Hits','Playlist · Cinema and new releases','leo',track('leo').art],['Malayalam Hits','Playlist · Cinema and new releases','premalu',track('premalu').art],['English Pop','Playlist · Global discovery','taylor-swift',track('taylor-swift').art],['Hollywood','Playlist · Global discovery','the-weeknd',track('the-weeknd').art],['Lo-Fi Focus','Playlist · Sonora','lofi-desk',track('lofi-desk').art],['Workout','Playlist · Sonora','pulse-check',track('pulse-check').art]]; return `<div class="content"><div class="library-toolbar"><h1>Your Library</h1><div class="view-toggles"><button title="List view">${icons.list}</button><button title="Grid view">${icons.grid}</button></div></div><div class="chip-row"><button class="chip active">Playlists</button><button class="chip">Artists</button><button class="chip">Albums</button></div><section>${collections.map(([name,meta,id,art])=>`<article class="library-row" data-track="${id}" tabindex="0">${art?`<img src="${art}" alt=""/>`:`<div class="mini-placeholder liked">♥</div>`}<div><b>${name}</b><span>${meta.replace('${n}',String(window.player?.liked.size||0))}</span></div><span class="type">Playlist</span><span class="type">${id==='liked'?'Saved':'Updated today'}</span></article>`).join('')}</section></div>`; }
  function profile(){const user=localStorage.getItem('sonora-user')||'Priya Rao',initials=user.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();return `<div class="content"><section class="profile-hero"><div class="profile-avatar">${esc(initials)}</div><div><div class="overline">PROFILE</div><h1>${esc(user)}</h1><p>12 public playlists · 38 followers · Bengaluru, IN</p><button class="text-link signout-link" data-sign-out>Sign out</button></div></section>${section('Public playlists',[tracks[0],tracks[9],tracks[6],tracks[4]],true)}<section class="section"><div class="section-head"><h2>Top artists this month</h2></div><div class="card-row">${artists.slice(0,4).map(a=>card(a,true)).join('')}</div></section></div>`;}
  function settings(){ const settings=[['Private session','Listen anonymously for this session.',false],['Autoplay','Keep music playing with similar tracks when your queue ends.',true],['Show friend activity','Let friends see what you are listening to.',true],['Animated canvas','Show animated color on now playing artwork.',false],['Offline mode','Only play downloaded placeholder tracks.',false]];return `<div class="content"><h1 class="page-heading">Settings</h1><section class="section setting-list"><div class="section-head"><h2>Playback</h2></div>${settings.map(([name,desc,on])=>`<div class="setting"><div><h3>${name}</h3><p>${desc}</p></div><button class="switch ${on?'active':''}" data-switch aria-label="Toggle ${name}" aria-pressed="${on}"></button></div>`).join('')}</section><section class="section setting-list"><div class="section-head"><h2>About this project</h2></div><p style="color:#b3b3b3;max-width:720px;line-height:1.65">Sonora is an original, educational streaming UI built with plain HTML, CSS and JavaScript. Its names, iconography and illustrated placeholder covers are original and it does not include copyrighted recordings.</p></section></div>`;}
  function screen(){ return ({home,playlist,liked,recently,search:searchPage,library,profile,settings}[page] || home)(); }

  function recordRecent(id){let history=JSON.parse(localStorage.getItem('sonora-recent')||'[]').filter(x=>x!==id);history.unshift(id);localStorage.setItem('sonora-recent',JSON.stringify(history.slice(0,12)));}
  function mount(){ const root=document.getElementById('app'); if(!root) return; document.body.classList.toggle('dark',localStorage.getItem('sonora-theme')!=='light'); window.player=new window.VisualPlayer(tracks); root.innerHTML=`<main class="app-shell">${sidebar()}<section class="main-panel"><div class="main-scroll">${topbar()}<div id="page-content">${screen()}</div></div></section>${playerMarkup()}</main>${queueMarkup()}<div class="toast-region" aria-live="polite"></div>`; window.player.init(); wire(); window.SonoraMotion.reveal(); const search=document.getElementById('global-search'); const params=new URLSearchParams(location.search),query=params.get('q')||'',auth=params.get('auth');search.value=query; if(page==='search') search.focus({preventScroll:true}); if(auth==='signup'||auth==='signin')setTimeout(()=>app.openAuth(auth),460); }
  function rerenderPage(){ const target=document.getElementById('page-content');if(!target)return;target.innerHTML=screen();window.player.paint(); }
  function updateSearch(value){ if(page==='search'){document.getElementById('search-results').innerHTML=searchResults(value);history.replaceState({},'',`search.html${value?`?q=${encodeURIComponent(value)}`:''}`);window.player.paint();return;}document.querySelectorAll('[data-search]').forEach(el=>{el.style.display=window.SonoraSearch.matches({title:el.dataset.search},value)?'':'none';}); }
  function wire(){
    document.addEventListener('click', e=>{
      const carouselControl=e.target.closest('[data-carousel-next],[data-carousel-prev]');if(carouselControl){const row=carouselControl.closest('.carousel-section')?.querySelector('[data-carousel-track]');if(row){row.scrollBy({left:(carouselControl.hasAttribute('data-carousel-next')?1:-1)*Math.max(250,row.clientWidth*.82),behavior:'smooth'});}return;}
      const play=e.target.closest('[data-play-track]'); if(play){e.preventDefault();window.player.load(play.dataset.playTrack);recordRecent(play.dataset.playTrack);return;}
      const playContainer=e.target.closest('[data-track]'); if(playContainer && !e.target.closest('button,a')){window.player.load(playContainer.dataset.track);recordRecent(playContainer.dataset.track);return;}
      const like=e.target.closest('[data-like-track]');if(like){e.preventDefault();e.stopPropagation();window.player.toggleLike(like.dataset.likeTrack);return;}
      if(e.target.closest('[data-open-sidebar]'))document.getElementById('sidebar').classList.add('drawer-open');
      if(e.target.closest('[data-close-sidebar]'))document.getElementById('sidebar').classList.remove('drawer-open');
      if(e.target.closest('[data-close-queue]'))document.getElementById('queue-panel').classList.remove('open');
      const libraryFilter=e.target.closest('[data-library-filter]');if(libraryFilter){const kind=libraryFilter.dataset.libraryFilter;document.querySelectorAll('[data-library-filter]').forEach(btn=>{const active=btn===libraryFilter;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active);});document.querySelectorAll('.library-entry').forEach(item=>item.hidden=!item.classList.contains(`${kind.slice(0,-1)}-entry`));return;}
      if(e.target.closest('[data-create-playlist]'))app.toast('New playlist created — ready for your first track.');
      if(e.target.closest('[data-theme-toggle]'))app.toggleTheme();
      if(e.target.closest('[data-auth]'))app.openAuth(e.target.closest('[data-auth]').dataset.auth);
      if(e.target.closest('[data-premium]'))app.toast('Premium preview: uninterrupted listening is on the way.');
      if(e.target.closest('[data-install]'))app.toast('Install is simulated in this educational demo.');
      if(e.target.closest('[data-notifications]'))app.toast('You are all caught up.');
      if(e.target.closest('[data-profile]'))location.href='profile.html';
      if(e.target.closest('[data-sign-out]')){localStorage.removeItem('sonora-user');app.toast('You have signed out.');setTimeout(()=>location.href='home.html',380);}
      if(e.target.closest('[data-download]'))app.toast('Playlist saved for offline listening.');
      if(e.target.closest('[data-collection-like]')){e.target.closest('[data-collection-like]').classList.toggle('active');app.toast('Playlist saved to Your Library.');}
      if(e.target.closest('[data-switch]')){const el=e.target.closest('[data-switch]');el.classList.toggle('active');el.setAttribute('aria-pressed',el.classList.contains('active'));}
      const genre=e.target.closest('[data-search-genre]');if(genre){const t=track(genre.dataset.searchGenre);location.href=`search.html?q=${encodeURIComponent(t.category.split(' ')[0])}`;}
    });
    let drag=null;
    document.addEventListener('pointerdown',e=>{const row=e.target.closest('[data-carousel-track]');if(!row||e.target.closest('button,a'))return;drag={row,startX:e.clientX,startLeft:row.scrollLeft,moved:false};row.classList.add('is-dragging');row.setPointerCapture?.(e.pointerId);});
    document.addEventListener('pointermove',e=>{if(!drag)return;const distance=e.clientX-drag.startX;if(Math.abs(distance)>4)drag.moved=true;drag.row.scrollLeft=drag.startLeft-distance;});
    document.addEventListener('pointerup',()=>{if(!drag)return;drag.row.classList.remove('is-dragging');drag=null;});
    document.addEventListener('keydown',e=>{const onInput=['INPUT','TEXTAREA'].includes(document.activeElement.tagName);if(onInput)return;if(e.code==='Space'){e.preventDefault();window.player.toggle();}if(e.key==='ArrowRight')window.player.next();if(e.key==='ArrowLeft')window.player.previous();if(e.key.toLowerCase()==='m')window.player.toggleMute();if(e.key.toLowerCase()==='l')window.player.toggleLike();if(e.key==='Escape'){document.getElementById('sidebar')?.classList.remove('drawer-open');document.getElementById('queue-panel')?.classList.remove('open');}});
    document.getElementById('global-search')?.addEventListener('input',e=>updateSearch(e.target.value));
    document.getElementById('global-search')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&page!=='search')location.href=`search.html?q=${encodeURIComponent(e.target.value)}`;});
  }
  const app={
    toast(message){ const region=document.querySelector('.toast-region');if(!region)return;const el=document.createElement('div');el.className='toast';el.innerHTML=`<i></i><span>${esc(message)}</span>`;region.append(el);setTimeout(()=>{el.classList.add('out');setTimeout(()=>el.remove(),270);},2800); },
    toggleTheme(){const root=document.body;const light=root.classList.contains('dark');root.classList.toggle('dark',!light);localStorage.setItem('sonora-theme',light?'light':'dark');document.querySelectorAll('[data-theme-toggle]').forEach(btn=>{btn.innerHTML=light?icons.moon:icons.sun;btn.title=light?'Switch to dark mode':'Switch to light mode';btn.setAttribute('aria-label',btn.title);});this.toast(light?'Light mode enabled':'Dark mode enabled');},
    openAuth(mode){const existing=document.querySelector('.modal-backdrop');if(existing){existing.remove();return;}const signUp=mode==='signup';const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<section class="modal auth-modal" role="dialog" aria-modal="true" aria-label="${signUp?'Create your account':'Sign in'}"><button class="close" aria-label="Close">×</button><img src="${A}logo/sonora-mark.svg" width="38" height="38" alt=""/><h2>${signUp?'Create your Sonora account':'Welcome back'}</h2><p>${signUp?'Save playlists, likes and your listening history.':'Sign in to see your profile, saved tracks and playlists.'}</p><form class="auth-form"><label>Display name<input name="name" required minlength="2" placeholder="Your name" value="${signUp?'':'Priya'}"/></label><label>Email<input name="email" required type="email" placeholder="you@example.com"/></label><label>Password<input name="password" required type="password" minlength="4" placeholder="••••••••"/></label><button class="cta" type="submit">${signUp?'Create account':'Sign in'}</button></form><small>Demo account flow — no information leaves this browser.</small></section>`;modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.close'))modal.remove();});modal.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name').trim();localStorage.setItem('sonora-user',name);modal.remove();this.toast(`Welcome, ${name}!`);setTimeout(()=>location.reload(),420);});document.body.append(modal);modal.querySelector('input')?.focus();},
    toggleQueue(){document.getElementById('queue-panel')?.classList.toggle('open');},
    openLyrics(){const old=document.querySelector('.modal-backdrop');if(old){old.remove();return;}const t=window.player.track;const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="Lyrics"><button class="close" aria-label="Close lyrics">×</button><h2>${esc(t.title)}</h2><p>${esc(t.artist)}</p><div class="lyrics-lines"><p class="active">Placeholder lyrics move with the feeling.</p><p>Every line is an original note in the night.</p><p>Follow the glow and let the rhythm breathe.</p><p>Music is where the small moments meet.</p></div><small style="color:#999">Lyrics preview · original placeholder text</small></section>`;modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.close'))modal.remove();});document.body.append(modal);},
    refreshLikes(){ if(page==='liked')rerenderPage(); else {document.querySelectorAll('[data-like-track]').forEach(el=>{const id=el.dataset.likeTrack;el.classList.toggle('active',window.player.isLiked(id));el.innerHTML=icons.heart(window.player.isLiked(id));});} }
  };window.SonoraApp=app;mount();
})();
